Fall back to 7-Zip when zip file uses unsupported compression type
Fall back to 7-Zip when an uploaded zip file uses a compression type
that Python's zipfile module doesn't support. This avoids errors like
the following:

    NotImplementedError: compression type 9 (deflate64)